name: Exporter-Tiny
abstract: "an exporter with the features of Sub::Exporter but only core dependencies"
abstract_html: 'an exporter with the features of <span class="text-dark">Sub::Exporter</span><br> but only core dependencies'
github: https://github.com/tobyink/p5-exporter-tiny
issues: https://github.com/tobyink/p5-exporter-tiny/issues
copyright: "Copyright © 2023 Toby Inkster. All rights reserved."
theme:
  light: "#cefaeb"
  dark: "#25205c"
  primary: "#264a5a"
  secondary: "#8f4158"
  info: "#b3a7ae"
  success: "#2ea05b"
  warning: "#e5c930"
  danger: "#ef1a26"
homepage:
  animation: waves1
